### ISSUE TITLE
[To-Do] Feature Enhancement

### ISSUE THREAD

**Issue by shjucsd** [cse110-sp24-group30/cse110-sp24-group30#108]
### Objectives
The objective of this issue to make minor changes in ToDo like fixing the category-select id issue, random title generation for newly created tasks, updating labels to have it consistent with calendar. 

### Acceptance Criteria
- [ ] Category-Select identical id issue resolved
- [ ] Random Title Generated correctly stored in localStorage and displayed
- [ ] New labels - Personal, Work, School, Other
- [ ] JSDoc comments for all functions

### Assignees
- @shjucsd 

### Additional Notes <Optional>
Potentially change color scheme of labels, make minor changes to font styles to make things stand out.
