### ISSUE TITLE
[Calendar] Sync Calendar delete with Todo

### ISSUE THREAD

**Issue by shjucsd** [cse110-sp24-group30/cse110-sp24-group30#147]
### Objectives
Sync the Todo page if a task is deleted from calendar

### Acceptance Criteria
- [ ] Correctly updates the local storage
- [ ] Doesn't display the deleted task
- [ ] Updates count on the top of the column it was deleted from

### Assignees
- @shjucsd
