### ISSUE TITLE
[Todo] Setting up Todo List canvas

### ISSUE THREAD

**Issue by adironene** [cse110-sp24-group30/cse110-sp24-group30#51]
# [Todo] Setting up Todo List canvas

### Objectives
Set up the HTML page for the Todo List canvas
### Acceptance Criteria
- [x] Set up the 3 columns with a few dummy tasks hard coded
- [x] Set up page title
- [x] Include the dashboard headers with navigation to other pages
### Assignees
- @shjucsd 
- @UKCSD 
- @alt012ucsd 
- @ChooChooChao
