### ISSUE TITLE
[To-Do] Tags for Categories

### ISSUE THREAD

**Issue by adironene** [cse110-sp24-group30/cse110-sp24-group30#52]
[To-Do] Tags for Categories
### Objectives
Support tags for the todo list categories
### Acceptance Criteria
- [ ] Following tags: School, Chores, Work, Self-care, People
- [ ] any other categories not covered above
- [ ] each task is able to select one or more tags
- [ ] each task can delete tags once added
### Assignees
- @UKCSD 
- @shjucsd 
- @ChooChooChao 
- @alt012ucsd

**Comment by shjucsd** [comment]
Proposed changes to acceptance criteria:

- [x] Tags: Self, School, Work, Other
- [x] Each task able to select 1 tag which can be changed anytime

Considering the new acceptance criteria, we have completed this issue with [this PR](https://github.com/cse110-sp24-group30/cse110-sp24-group30/pull/64).
