### ISSUE TITLE
[To-Do] Modify + Add Tasks

### ISSUE THREAD

**Issue by adironene** [cse110-sp24-group30/cse110-sp24-group30#54]
[To-Do] Modify + Add Tasks
### Objectives
supporting adding new tasks and modify tasks
### Acceptance Criteria
- [ ] User is able to edit tasks 
- [ ] edit date
- [ ] edit description
- [ ] edit category
- [ ] edit title
- [x] User is able to create new tasks
- [ ] on creation, prompt for title and due date
- [ ] other fields are optional
### Assignees
- @UKCSD 
- @ChooChooChao 
- @shjucsd 
- @alt012ucsd

**Comment by shjucsd** [comment]
Proposed changes to acceptance criteria:

- [x] New task created with default template (so that consistent with how journals created)
- [x] User able to edit tasks
- [x] User able to delete tasks
- [x] Edit date
- [x] Edit title
- [x] Edit category/label
